name: CI
on:
  push:
    branches:
    - main
    - v1.x
  pull_request:
    branches:
    - main
    - v1.x

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:

    - name: Check formatting
      uses: JohnnyMorganz/stylua-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check lua/
